{% set version = "1.0.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-purrr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/purrr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/purrr/purrr_{{ version }}.tar.gz
  sha256: 2c1bc6bb88433dff0892b41136f2f5c23573b335ff35a4775c72aa57b48bbb63

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-cli >=3.4                  # [build_platform != target_platform]
    - r-lifecycle >=1.0.3          # [build_platform != target_platform]
    - r-magrittr >=1.5             # [build_platform != target_platform]
    - r-rlang >=0.4.10             # [build_platform != target_platform]
    - r-vctrs >=0.5                # [build_platform != target_platform]
  host:
    - r-base
    - r-cli >=3.4
    - r-lifecycle >=1.0.3
    - r-magrittr >=1.5
    - r-rlang >=0.4.10
    - r-vctrs >=0.5
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-cli >=3.4
    - r-lifecycle >=1.0.3
    - r-magrittr >=1.5
    - r-rlang >=0.4.10
    - r-vctrs >=0.5

test:
  commands:
    - $R -e "library('purrr')"           # [not win]
    - "\"%R%\" -e \"library('purrr')\""  # [win]

about:
  home: https://purrr.tidyverse.org
  dev_url: https://github.com/tidyverse/purrr
  doc_url: https://purrr.tidyverse.org/reference/index.html
  license: MIT
  summary: A complete and consistent functional programming toolkit for R.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
