{% set version = "0.3.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-purrr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/purrr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/purrr/purrr_{{ version }}.tar.gz
  sha256: 23ebc93bc9aed9e7575e8eb9683ff4acc0270ef7d6436cc2ef4236a9734840b2

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-magrittr >=1.5             # [build_platform != target_platform]
    - r-rlang >=0.3.1              # [build_platform != target_platform]
  host:
    - r-base
    - r-magrittr >=1.5
    - r-rlang >=0.3.1
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-magrittr >=1.5
    - r-rlang >=0.3.1

test:
  commands:
    - $R -e "library('purrr')"           # [not win]
    - "\"%R%\" -e \"library('purrr')\""  # [win]

about:
  home: http://purrr.tidyverse.org, https://github.com/tidyverse/purrr
  license: GPL-3.0-only
  summary: A complete and consistent functional programming toolkit for R.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: purrr
# Title: Functional Programming Tools
# Version: 0.3.2
# Authors@R: c( person("Lionel", "Henry", , "lionel@rstudio.com", c("aut", "cre")), person("Hadley", "Wickham", , "hadley@rstudio.com", "aut"), person("RStudio", role = c("cph", "fnd")) )
# Description: A complete and consistent functional programming toolkit for R.
# License: GPL-3 | file LICENSE
# URL: http://purrr.tidyverse.org, https://github.com/tidyverse/purrr
# BugReports: https://github.com/tidyverse/purrr/issues
# Depends: R (>= 3.1)
# Imports: magrittr (>= 1.5), rlang (>= 0.3.1)
# Suggests: covr, crayon, dplyr (>= 0.7.8), knitr, rmarkdown, testthat, tibble, tidyselect
# VignetteBuilder: knitr
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# NeedsCompilation: yes
# Packaged: 2019-03-15 15:56:56 UTC; lionel
# Author: Lionel Henry [aut, cre], Hadley Wickham [aut], RStudio [cph, fnd]
# Maintainer: Lionel Henry <lionel@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-03-15 18:20:02 UTC
