{% set version = '0.2.5' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-purrr
  version: {{ version|replace("-", "_") }}

source:
  fn: purrr_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/purrr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/purrr/purrr_{{ version }}.tar.gz
  sha256: a4a68a453f5341ae84c3e8d77b0587ed586f36eb51f64f1315750eabfe1f8535

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-magrittr >=1.5
    - r-rlang >=0.1
    - r-tibble
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-magrittr >=1.5
    - r-rlang >=0.1
    - r-tibble

test:
  commands:
    - $R -e "library('purrr')"           # [not win]
    - "\"%R%\" -e \"library('purrr')\""  # [win]

about:
  home: http://purrr.tidyverse.org, https://github.com/tidyverse/purrr
  license: GPL-3
  summary: A complete and consistent functional programming toolkit for R.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
