travis:
  secure:
    BINSTAR_TOKEN: Na72YmYONLQXizQUMIrqQ/4loCFvQfpRLM5VpbVppvxGdGqomgIh8wyUxvGlRj+tUYqnCGCuMxBre5+HNSV5cUNWHp+MGy2DjG8vHN56eqDmsT7nJf0NArYZ4I1kIeVNBp5j9ZcAft2BF8ZB7o8Kff/KvbJfYzaLq2vltW4WB5Wl1oQ6WoJqHOmgWMCI7WQXFSb9A5x8K7+6E/NIA0uY1+I9/arNzYpsR1fJTRZbrtnVO6cNmLFHhijUCGuhjzCQu7XwnizUOn/etumNaEZF4T9ADdP3ad7WLdKh8eZ0FFjGXMny09jcP7sVe+JN8UFjS6l8i4TTQ5/PUf8d2d37TZ1/6wBIpB8cIOoBVmzw2H2etvALu6uXzn6oSUyOkCgSGD1EOjx2ASRGhN4cbeCa9P/MLLsQw6jl+XyhF/lSmo69OInwnRXPaJLNl1ccIDGL/+Jz1hx8wUx662Qjm+aF6aG10H+WC2QTvfdfDIz83Qj9WPfdEGhnPyEqahb6JqCXRnqiP7BS+lR/KZVOzDQUNKVES7kBeNOUW64Q/HVk8LCDdRU47k11SRQyVNdcjJrCWCnj2lWvJIaG0Bsj9z57n8qd5w3WSJ7+goYbIUN5agQBJelXhdDsC9pK3ANdLZtlLfbBZutGUXzdNQWl8XU8gwrA+Ap8PxLC/Bkp9Ildv88=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
